-- Add comprehensive project ideas across all categories

-- Web Development Projects (100 projects)
INSERT INTO public.projects (title, description, detailed_description, project_type, difficulty, category, tech_stack, learning_outcomes, estimated_duration, prerequisites) VALUES
('E-Learning Platform', 'Build an online course platform with video streaming', 'Create a comprehensive e-learning platform featuring video streaming, course management, student progress tracking, quizzes, and certificates. Implement user authentication, payment integration, and interactive learning features.', 'major', 'advanced', 'Web Development', ARRAY['React', 'Node.js', 'MongoDB', 'AWS S3', 'Stripe'], ARRAY['Video streaming implementation', 'Payment gateway integration', 'Complex state management', 'Cloud storage'], '10-12 weeks', ARRAY['Advanced React', 'Backend development', 'Database design']),

('Real-time Chat Application', 'Build a messaging app with WebSocket', 'Develop a real-time chat application with private messaging, group chats, file sharing, typing indicators, and read receipts. Learn WebSocket implementation and real-time communication protocols.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Socket.io', 'Node.js', 'MongoDB'], ARRAY['WebSocket implementation', 'Real-time communication', 'Event-driven architecture'], '3-4 weeks', ARRAY['JavaScript fundamentals', 'Basic React']),

('Job Board Platform', 'Create a job listing and application platform', 'Build a job board where companies can post jobs and candidates can apply. Include features like resume upload, job filtering, application tracking, and email notifications.', 'major', 'intermediate', 'Web Development', ARRAY['Vue.js', 'Express', 'PostgreSQL', 'Redis'], ARRAY['Job matching algorithms', 'File upload handling', 'Email integration', 'Search optimization'], '8-10 weeks', ARRAY['Frontend framework knowledge', 'Backend basics']),

('Restaurant Menu Builder', 'Digital menu creator for restaurants', 'Create a tool for restaurants to build digital menus with images, pricing, categories, and allergen information. Include QR code generation for contactless ordering.', 'mini', 'beginner', 'Web Development', ARRAY['HTML', 'CSS', 'JavaScript', 'Bootstrap'], ARRAY['CRUD operations', 'Image handling', 'QR code generation', 'Print layouts'], '2-3 weeks', ARRAY['HTML/CSS basics', 'Basic JavaScript']),

('Fitness Tracker Dashboard', 'Track workouts and nutrition', 'Build a fitness tracking application with workout logging, nutrition tracking, progress charts, and goal setting. Integrate with fitness APIs for exercise data.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Chart.js', 'Node.js', 'MySQL'], ARRAY['Data visualization', 'API integration', 'Local storage', 'Progressive web apps'], '4-5 weeks', ARRAY['React basics', 'API consumption']),

('Music Streaming Service', 'Build a Spotify-like music platform', 'Create a music streaming service with playlists, recommendations, search, and audio playback. Implement features like lyrics display, artist pages, and social sharing.', 'major', 'advanced', 'Web Development', ARRAY['React', 'Node.js', 'MongoDB', 'AWS S3', 'Elasticsearch'], ARRAY['Audio streaming', 'Recommendation algorithms', 'Search optimization', 'Content delivery'], '12-14 weeks', ARRAY['Advanced full-stack', 'Audio processing basics']),

('Event Management System', 'Platform for organizing events', 'Develop an event management platform with ticketing, attendee management, schedules, and check-in systems. Include calendar integration and email reminders.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Firebase', 'Tailwind CSS'], ARRAY['Calendar integration', 'QR code ticketing', 'Real-time updates', 'Email automation'], '3-4 weeks', ARRAY['React fundamentals', 'Firebase basics']),

('News Aggregator', 'Curate news from multiple sources', 'Build a news aggregation platform that pulls articles from various sources, categorizes them, and provides personalized feeds. Implement sentiment analysis and trending topics.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Node.js', 'News API', 'Redis'], ARRAY['API aggregation', 'Caching strategies', 'Content filtering', 'Sentiment analysis'], '3-4 weeks', ARRAY['API integration', 'React knowledge']),

('Online Code Editor', 'Browser-based code editor with execution', 'Create an online IDE supporting multiple programming languages with syntax highlighting, code execution, and collaboration features.', 'major', 'advanced', 'Web Development', ARRAY['React', 'Monaco Editor', 'Docker', 'WebAssembly'], ARRAY['Code execution sandboxing', 'Real-time collaboration', 'Syntax highlighting', 'Container management'], '10-12 weeks', ARRAY['Advanced JavaScript', 'System design', 'Security concepts']),

('Travel Booking Platform', 'Book flights, hotels, and activities', 'Develop a comprehensive travel booking platform with flight search, hotel reservations, activity bookings, and itinerary planning. Integrate multiple travel APIs.', 'major', 'advanced', 'Web Development', ARRAY['Next.js', 'TypeScript', 'PostgreSQL', 'Stripe', 'Google Maps API'], ARRAY['Multi-API integration', 'Complex booking logic', 'Payment processing', 'Map integration'], '12-16 weeks', ARRAY['TypeScript proficiency', 'Payment systems', 'API orchestration']),

('Expense Tracker', 'Personal finance management app', 'Build an expense tracking application with categories, budgets, reports, and bank integration. Include data visualization and export features.', 'mini', 'beginner', 'Web Development', ARRAY['React', 'Chart.js', 'LocalStorage'], ARRAY['Budget management', 'Data visualization', 'Local data storage', 'Export to CSV'], '2-3 weeks', ARRAY['React basics', 'JavaScript fundamentals']),

('Photo Gallery CMS', 'Manage and display photo collections', 'Create a content management system for photo galleries with albums, tagging, search, and sharing capabilities. Include image optimization and lazy loading.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Node.js', 'Sharp', 'AWS S3'], ARRAY['Image optimization', 'Lazy loading', 'CDN integration', 'Metadata management'], '3-4 weeks', ARRAY['React knowledge', 'Image processing basics']),

('Survey Builder Platform', 'Create and analyze surveys', 'Build a platform to create surveys with various question types, collect responses, and analyze results with charts and statistics.', 'mini', 'intermediate', 'Web Development', ARRAY['Vue.js', 'Node.js', 'MongoDB', 'Chart.js'], ARRAY['Form builder patterns', 'Data analysis', 'Visualization', 'Export functionality'], '4-5 weeks', ARRAY['Vue.js basics', 'Backend fundamentals']),

('Wiki Platform', 'Collaborative knowledge base', 'Develop a wiki-style knowledge base with markdown support, version control, search, and collaboration features.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Node.js', 'PostgreSQL', 'Markdown'], ARRAY['Version control', 'Markdown parsing', 'Search implementation', 'Collaborative editing'], '4-5 weeks', ARRAY['React knowledge', 'Git concepts']),

('Appointment Booking System', 'Schedule appointments online', 'Create an appointment scheduling system with calendar view, notifications, and integration with popular calendar apps.', 'mini', 'intermediate', 'Web Development', ARRAY['React', 'Node.js', 'MongoDB', 'Calendar API'], ARRAY['Calendar integration', 'Scheduling algorithms', 'Email notifications', 'Time zone handling'], '3-4 weeks', ARRAY['React basics', 'API integration'])